# Generated by Django 3.1.2 on 2020-10-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='views',
            new_name='view',
        ),
    ]
