# Generated by Django 3.1.2 on 2020-10-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
